CREATE TABLE [dbo].[TblMst_Airport] (
    [SNo]                               INT            IDENTITY (1, 1) NOT NULL,
    [AirportCode]                       CHAR (3)       NOT NULL,
    [AirportName]                       NVARCHAR (100) NOT NULL,
    [CitySNo]                           INT            NOT NULL,
    [CityCode]                          CHAR (3)       NOT NULL,
    [CityName]                          NVARCHAR (100) NOT NULL,
    [CountrySNo]                        INT            NOT NULL,
    [CountryCode]                       CHAR (2)       NOT NULL,
    [CountryName]                       VARCHAR (100)  NOT NULL,
    [IsDayLightSaving]                  BIT            NULL,
    [IsDimensionMandatory]              BIT            CONSTRAINT [DF_TblMst_Airport_IsDimensionMandatory] DEFAULT ((0)) NULL,
    [IsActive]                          BIT            NOT NULL,
    [CreatedOn]                         DATETIME       NOT NULL,
    [CreatedBy]                         INT            NOT NULL,
    [UpdatedOn]                         DATETIME       NOT NULL,
    [UpdatedBy]                         INT            NOT NULL,
    [EventType]                         INT            NULL,
    [IsCraMasterTransfer]               TINYINT        NULL,
    [IsEmailAlertonoffloadedCargo]      BIT            NULL,
    [SendEmail_GetTotalUnplandShipment] BIT            NULL,
    [IsDefaultAirport]                  BIT            NULL,
    [IsDoChargeApplicable]              BIT            NULL,
    [IsSync]                            BIT            NULL,
    [LastChangeDateTime]                DATETIME       NULL,
    [AutoBuildup]                       BIT            CONSTRAINT [autobuildup_forairport] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_TblMst_Airport] PRIMARY KEY CLUSTERED ([SNo] ASC)
);

