CREATE TABLE [dbo].[TblTrn_TenantSetupProcessLog] (
    [inSetupID]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [inTenantID]                 INT            NOT NULL,
    [inProductID]                INT            NOT NULL,
    [btIsDBSetup]                BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsDBSetup] DEFAULT ((0)) NOT NULL,
    [dtDBSetupComplete]          DATETIME       NULL,
    [btIsAppURLSetup]            BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsAppURLSetup] DEFAULT ((0)) NOT NULL,
    [dtAppURLSetupComplete]      DATETIME       NULL,
    [vcAppURL]                   NVARCHAR (250) NULL,
    [btIsApplicationHost]        BIT            NULL,
    [dtApplicationHostCompleted] DATETIME       NULL,
    [btIsAPIURLSetup]            BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsAPIURLSetup] DEFAULT ((0)) NOT NULL,
    [dtAPIURLSetupComplete]      DATETIME       NULL,
    [vcAPIURL]                   NVARCHAR (250) NULL,
    [btIsWSSetup]                BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsWSSetup] DEFAULT ((0)) NOT NULL,
    [dtWSSetupComplete]          DATETIME       NULL,
    [btIsSetupProcessComplete]   BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsSetupProcessComplete] DEFAULT ((0)) NOT NULL,
    [btIsActive]                 BIT            CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_btIsActive] DEFAULT ((1)) NOT NULL,
    [dtCreatedOn]                DATETIME       CONSTRAINT [DF_TblTrn_TenantSetupProcessLog_dtCreatedOn] DEFAULT (getdate()) NOT NULL,
    [inCreatedBy]                BIGINT         NOT NULL,
    [dtModifiedOn]               DATETIME       NULL,
    [dtModifiedBy]               BIGINT         NULL,
    [btAdminCreationCompleted]   BIT            CONSTRAINT [DF__TblTrn_Te__btAdm__673F4B05] DEFAULT ((0)) NOT NULL,
    [btIsEmailSend]              BIT            NULL,
    [dtAdminCreationComplete]    DATETIME       NULL,
    [dtEmailSend]                DATETIME       NULL,
    CONSTRAINT [PK_TblTrn_TenantSetupProcessLog] PRIMARY KEY CLUSTERED ([inSetupID] ASC),
    CONSTRAINT [FK_TblTrn_TenantSetupProcessLog_AbpTenants] FOREIGN KEY ([inTenantID]) REFERENCES [dbo].[AbpTenants] ([Id]),
    CONSTRAINT [FK_TblTrn_TenantSetupProcessLog_TblMst_Product] FOREIGN KEY ([inProductID]) REFERENCES [dbo].[TblMst_Product] ([inProductID])
);

