CREATE TABLE [dbo].[TblTrn_UserDetails] (
    [inUserDetailsID]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [inTenantID]              INT           NULL,
    [inUserTypeID]            INT           NOT NULL,
    [vcFirstName]             VARCHAR (50)  NOT NULL,
    [vcLastName]              VARCHAR (50)  NOT NULL,
    [vcCompanyName]           VARCHAR (120) NOT NULL,
    [inAirlineID]             INT           NULL,
    [inDepartmentID]          INT           NOT NULL,
    [vcDepartmentName]        VARCHAR (100) NOT NULL,
    [inDesignationID]         INT           NULL,
    [vcDesignation]           VARCHAR (100) NULL,
    [vcServicesLookingFor]    VARCHAR (100) NULL,
    [inCityID]                INT           NOT NULL,
    [inCountryID]             INT           NOT NULL,
    [vcContact]               NVARCHAR (15) NOT NULL,
    [vcRepresentingAirlines]  VARCHAR (100) NOT NULL,
    [vcRepresentingCountries] VARCHAR (100) NULL,
    [inIndustryID]            INT           NULL,
    [vcIndustryName]          VARCHAR (100) NULL,
    [btIsActive]              BIT           CONSTRAINT [DF_TblTrn_UserDetails_btIsActive] DEFAULT ((1)) NOT NULL,
    [dtCreatedOn]             DATETIME      CONSTRAINT [DF_TblTrn_UserDetails_dtCreatedOn] DEFAULT (getdate()) NOT NULL,
    [inCreatedBy]             BIGINT        NOT NULL,
    [dtModifiedOn]            DATETIME      NULL,
    [inModifiedBy]            BIGINT        NULL,
    [inUserID]                BIGINT        NOT NULL,
    CONSTRAINT [PK_TblTrn_UserDetails] PRIMARY KEY CLUSTERED ([inUserDetailsID] ASC),
    FOREIGN KEY ([inUserID]) REFERENCES [dbo].[AbpUsers] ([Id]),
    CONSTRAINT [FK_TblTrn_UserDetails_AbpTenants] FOREIGN KEY ([inTenantID]) REFERENCES [dbo].[AbpTenants] ([Id]),
    CONSTRAINT [FK_TblTrn_UserDetails_TblMst_UserType] FOREIGN KEY ([inUserTypeID]) REFERENCES [dbo].[TblMst_UserType] ([inUserTypeID])
);

